name: t5-large
type: ConditionalGeneration
epochs: 1
per_device_batch_size: 32
real_batch_size: 1
bf16: True
eval_epochs: 0.1
early_stopping_patience: 3
max_length: 128
logging_steps: 1
learning_rate: 5e-5