name: google/flan-t5-xl
type: ConditionalGeneration
epochs: 5
per_device_batch_size: 1
real_batch_size: 32
bf16: True
eval_epochs: 1
early_stopping_patience: 3
max_length: 512
logging_steps: 1
learning_rate: 5e-5